

#ifndef __ZJV_CATEGORYDEFINE_H__
#define __ZJV_CATEGORYDEFINE_H__

namespace ZJVIDEO
{
    // 目标类别， 主类别和子类别
    enum OBJECT_CATEGORY
    {
        ZJV_CATEGORY_UNKNOWN = 0,
        // 人
        ZJV_CATEGORY_PERSON = ZJV_CATEGORY_UNKNOWN + 100,    // 子类别对应 PERSON_SUB_CATEGORY
            ZJV_PERSON_SUB_CATEGORY_PERSON_UNKNOWN  = ZJV_CATEGORY_PERSON + 1,
            ZJV_PERSON_SUB_CATEGORY_BODY            = ZJV_CATEGORY_PERSON + 2,
            ZJV_PERSON_SUB_CATEGORY_FACE            = ZJV_CATEGORY_PERSON + 3,
            ZJV_PERSON_SUB_CATEGORY_HEAD            = ZJV_CATEGORY_PERSON + 4,
            ZJV_PERSON_SUB_CATEGORY_HAND            = ZJV_CATEGORY_PERSON + 5,
            ZJV_PERSON_SUB_CATEGORY_HEADSHOULDER    = ZJV_CATEGORY_PERSON + 6,
            ZJV_PERSON_SUB_CATEGORY_UPPER_BODY      = ZJV_CATEGORY_PERSON + 7,
            ZJV_PERSON_SUB_CATEGORY_LOWER_BODY      = ZJV_CATEGORY_PERSON + 8,

        // 交通工具
        ZJV_CATEGORY_VEHICLE = ZJV_CATEGORY_UNKNOWN + 200,   // 子类别对应 VEHICLE_SUB_CATEGORY

            ZJV_VEHICLE_SUB_CATEGORY_UNKNOWN    = ZJV_CATEGORY_VEHICLE + 1,
            ZJV_VEHICLE_SUB_CATEGORY_CAR        = ZJV_CATEGORY_VEHICLE + 2,
            ZJV_VEHICLE_SUB_CATEGORY_TRUCK      = ZJV_CATEGORY_VEHICLE + 3,
            ZJV_VEHICLE_SUB_CATEGORY_BUS        = ZJV_CATEGORY_VEHICLE + 4,
            ZJV_VEHICLE_SUB_CATEGORY_VAN        = ZJV_CATEGORY_VEHICLE + 5,        
            ZJV_VEHICLE_SUB_CATEGORY_MOTORCYCLE = ZJV_CATEGORY_VEHICLE + 6,
            ZJV_VEHICLE_SUB_CATEGORY_BICYCLE    = ZJV_CATEGORY_VEHICLE + 7,
            ZJV_VEHICLE_SUB_CATEGORY_PEDESTRIAN = ZJV_CATEGORY_VEHICLE + 8,

        // 图像
        ZJV_CATEGORY_IMAGE = ZJV_CATEGORY_UNKNOWN + 300,    // 子类别对应 IMAGE_SUB_CATEGORY
            ZJV_IMAGE_SUB_CATEGORY_UNKNOWN = ZJV_CATEGORY_IMAGE + 1,
            ZJV_IMAGE_SUB_CATEGORY_WELDING = ZJV_CATEGORY_IMAGE + 2,    // 焊接图像
        ZJV_CATEGORY_MAX
    };

    // 属性类别
    enum ATTRIBUTE_CATEGORY
    {
        ZJV_ATTRIBUTE_UNKNOWN = 0,
        // 数值属性
        ZJV_ATTRIBUTE_VALUE_WELDSEAM_DEPTH = 1,                 // 焊缝深度
        ZJV_ATTRIBUTE_VALUE_WELDSEAM_FRONT_QUALITY = 2,         // 焊缝正面评分
        ZJV_ATTRIBUTE_VALUE_WELDSEAM_BACK_QUALITY = 3,          // 焊缝背面评分

        // 类别属性
        ZJV_ATTRIBUTE_CATEGORY_BASE = 999,                                  // 类别属性起点
        ZJV_ATTRIBUTE_CATEGORY_UNKNOWN = ZJV_ATTRIBUTE_CATEGORY_BASE,       // 未知类别属性
        ZJV_ATTRIBUTE_CATEGORY_WELDSEAM_STATUS = 1000,                      // 焊缝状态
            // 类别属性值
            ZJV_ATTRIBUTE_CATEGORY_VALUE_WELDSEAM_STATUS_INCOMPLETE,        // +1 未熔透
            ZJV_ATTRIBUTE_CATEGORY_VALUE_WELDSEAM_STATUS_NORMAL,            // +2 正常熔透
            ZJV_ATTRIBUTE_CATEGORY_VALUE_WELDSEAM_STATUS_OVER,              // +3 过熔透
            ZJV_ATTRIBUTE_CATEGORY_VALUE_WELDSEAM_STATUS_UNKNOWN,           // +4 未知状态

        ZJV_ATTRIBUTE_CATEGORY_OTHER = ZJV_ATTRIBUTE_CATEGORY_BASE + 1 + 100,          // 其他类别属性
            ZJV_ATTRIBUTE_CATEGORY_VALUE_OTHER_V1,
            ZJV_ATTRIBUTE_CATEGORY_VALUE_OTHER_V2,
            ZJV_ATTRIBUTE_CATEGORY_VALUE_OTHER_V3,
            ZJV_ATTRIBUTE_CATEGORY_VALUE_OTHER_V4,
        ZJV_ATTRIBUTE_MAX
        
    };
}

#endif //__ZJV_CATEGORYDEFINE_H__